# Complexity Assignment - c.pierik

# Exercise One
### 1. lmplement this algorithm in Python. Use the NumPy ndarray object foryour matrices;

In [16]:
import numpy as np

In [17]:
import numpy as np

def square_matrix_multiply(A, B):
    n = len(A)
    C = [[0] * n for _ in range(n)] #Initialize
    
    for i in range(n):# Iterate through rows of A
        for j in range(n):# Iterate through columns of B
            for k in range(n):# Iterate through elements of rows of A and columns of B
                C[i][j] += A[i][k] * B[k][j]# Compute the product and accumulate it in C
    return C

In [3]:
# Example
A = np. array([[1,2],[3,4]])
B= np.array([[5,2],[7,8]])

result=square_matrix_multiply(A, B)
print(result)

[[19, 18], [43, 38]]


### 2. Give the asymptotic time complexity of the above algorithm or your implementation (they should be the same). Justify and explain your answer

#### I think the time complexity of O(n^3), where n is the size of the square matrices A and B.
#### "for i = 1 to n do"--------------------n times;
#### "for j = 1 to n do"--------------------n times;
#### "cij = 0 for k = 1 to n do"----------n times;
#### "cij = cij + aik × bkj"----------------n times;
#### So, O(n* n* n) = O(n^3)

### Suggestion1. Implement the algorithm with nested lists and compare the algorithms on different sizes of matrices

### Suggestion2. Compare with built-in multiplication functions

In [18]:
import time

def generate_random_matrix(n):
    return [[np.random.randint(20) for _ in range(n)] for _ in range(n)]

# define the size
sizes = [100, 200, 500]
for size in sizes:
    A = generate_random_matrix(size)
    B = generate_random_matrix(size)
    
    # consuming time of built-in multiplication functions
    start_time = time.time()
    np_result = np.dot(A, B) 
    numpy_time = time.time() - start_time

    # consuming time of nested list implementation
    start_time = time.time()
    list_result = square_matrix_multiply(A, B)
    list_time = time.time() - start_time
    
    print(f"Matrix size: {size}x{size}")
    print(f"NumPy time: {numpy_time:.3f} s")
    print(f"Nested list time: {list_time:.3f} s")
    print()

Matrix size: 100x100
NumPy time: 0.000 s
Nested list time: 0.143 s

Matrix size: 200x200
NumPy time: 0.005 s
Nested list time: 1.268 s

Matrix size: 500x500
NumPy time: 0.126 s
Nested list time: 27.045 s



### Suggestion3. Look at multiplying more than two matrices, or at other operations on matrices

In [21]:
# let's try multiplying three matrices
def multiply_matrices(*matrices):
    result = matrices[0]
    for matrix in matrices[1:]:
        result = square_matrix_multiply(result, matrix)
    return result

In [19]:
# Example
A = generate_random_matrix(3)
B = generate_random_matrix(3)
C = generate_random_matrix(3)

print("random_matrix A:")
for row in A:
    print(row)
print("\nrandom_matrix B:")
for row in B:
    print(row)
print("\nrandom_matrix C:")
for row in C:
    print(row)

random_matrix A:
[1, 8, 12]
[10, 14, 10]
[16, 16, 12]

random_matrix B:
[19, 5, 18]
[0, 7, 14]
[17, 19, 19]

random_matrix C:
[19, 0, 17]
[3, 17, 15]
[4, 4, 11]


In [22]:
list_result = multiply_matrices(A, B, C)
print(list_result)

print()

np_result = np.dot(np.dot(A, B), C) 
print(np_result)

[[6536, 6345, 12064], [10118, 8010, 17416], [13872, 10100, 23076]]

[[ 6536  6345 12064]
 [10118  8010 17416]
 [13872 10100 23076]]


# Exercise Two
### 1. Describe and explain the algorithm. It should contain at least the following:

This algorithm, Square-Matrix-Multiply-Recursive (SMMRec), is a recursive implementation of matrix multiplication. 

1. "SMMRec(A,B):": accepts two matrices A and B as input.
2. "n = nr of rows of A": Define a variable n which is equal to the number of rows of A, also the size of A.
3. "let C be a new n × n matrix": Create a new square C with the same dimensions as A and B.
4. "if n == 1 then":If the size of the matrix is 1 × 1, the following operations are performed; otherwise, the chunked multiplication of the matrix is performed.
5. "quarter matrices A, B, and C":Divide the matrices A, B and C into four equal-sized sub-matrices.
6. "C11 = SMMRec(A11,B11) + SMMRec(A12,B21)""C12 = SMMRec(A11,B12) + SMMRec(A12,B22)""C21 = SMMRec(A21,B11) + SMMRec(A22,B21)""C22 = SMMRec(A21,B12) + SMMRec(A22,B22)": Calculate the value of C11 C12 C21 C22 separately.

**recursiveness:**
The base case of the recursion is when the size of the matrices becomes 1 × 1, the algorithm computes the product directly without further recursion.And in each recursion step, the algorithm divides the input matrices into four equal-sized submatrices. It then recursively multiplies these submatrices until the base case is reached, where it computes the product directly.

**divide-and-conquer:**
1. **Divide**:The algorithm divides the input matrices A, B, and C into four equal-sized submatrices.
2. **Conquer**: It recursively multiplies these submatrices. Each multiplication involves recursively calling the SMMRec function until the base case is reached, and then directly computing the product.
3. **Combine**: After computing the products of submatrices, the algorithm combines them to form the final result matrix C. The combination involves adding or summing the products of corresponding submatrices to form the corresponding submatrices of C.

### 2. Implement the recursive algorithm in Python. Reflect on which steps of the pseudocode were straightforward to implement and which hid a lot of complexity behind their language.

In [11]:
import numpy as np
def split_matrix(A):
    mid = len(A) // 2
    
    A11 = [row[:mid] for row in A[:mid]]
    A21 = [row[:mid] for row in A[mid:]]
    A12 = [row[mid:] for row in A[:mid]]
    A22 = [row[mid:] for row in A[mid:]]
    
    return A11, A12, A21, A22

def combine_matrices(C11, C12, C21, C22):
    n = len(C11)
    C = [[0 for _ in range(2 * n)] for _ in range(2 * n)]
    
    for i in range(n):
        for j in range(n):
            C[i][j] = C11[i][j]
            C[i][j + n] = C12[i][j]
            C[i + n][j] = C21[i][j]
            C[i + n][j + n] = C22[i][j]
    return C

def matrix_add(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A))] for i in range(len(A))]




def SMM_recursive(A, B):
    n = len(A)
    if n == 1:
        # Base case
        return [[A[0][0] * B[0][0]]]  
    
    else:
        
        A11, A12, A21, A22 = split_matrix(A)
        B11, B12, B21, B22 = split_matrix(B)

        # Recursive multiplications
        C11 = matrix_add(SMM_recursive(A11, B11), SMM_recursive(A12, B21))
        C12 = matrix_add(SMM_recursive(A11, B12), SMM_recursive(A12, B22))
        C21 = matrix_add(SMM_recursive(A21, B11), SMM_recursive(A22, B21))
        C22 = matrix_add(SMM_recursive(A21, B12), SMM_recursive(A22, B22))

       
        return combine_matrices(C11, C12, C21, C22)

In [19]:
# Example
def generate_random_matrix(n):
    return [[np.random.randint(20) for _ in range(n)] for _ in range(n)]

A = generate_random_matrix(4)
B = generate_random_matrix(4)
C = generate_random_matrix(4)

print("random_matrix A:")
for row in A:
    print(row)
print("\nrandom_matrix B:")
for row in B:
    print(row)
print("\nrandom_matrix C:")
for row in C:
    print(row)

random_matrix A:
[6, 8, 0, 13]
[16, 15, 2, 17]
[11, 9, 1, 17]
[19, 12, 1, 19]

random_matrix B:
[11, 15, 12, 19]
[15, 14, 8, 10]
[13, 2, 7, 14]
[15, 1, 0, 10]

random_matrix C:
[17, 7, 17, 7]
[1, 2, 1, 2]
[19, 9, 11, 15]
[14, 15, 1, 14]


In [22]:
C = SMM_recursive(A, B)
print("square matrix multiplyrecursive result:\n", C)

np_result = np.dot(A, B) # Check the results
print("np result:\n", np_result)

square matrix multiplyrecursive result:
 [[381, 215, 136, 324], [682, 471, 326, 652], [524, 310, 211, 483], [687, 474, 331, 685]]
np result:
 [[381 215 136 324]
 [682 471 326 652]
 [524 310 211 483]
 [687 474 331 685]]


**Straightforward Steps:**
1. Base case
2. Splitting matrices
3. Combining matrices

**Steps with Complexity behind:**
1. Matrix addition: Matrix addition involves adding corresponding elements of matrices together. We iterate over the matrices, accessing corresponding elements and adding them together in the matrix_add() function,
2. Recursive call: The algorithm computes the product of submatrices by performing addition and multiplication on the corresponding elements in the pseudocode.

### 3. Do a complexity analysis for the SMMRec algorithm. First comment on the complexity of the base case, divide step, conquer step, and combine step separately, then put it all together.
#### Use slides 20-21 of the lecture slides (pages 40-45 of the pdf) of Complexity lecture 2 as a guideline.
#### You do not have to do the tree analysis (slides 22-23), but do take aguess what the final complexity is.

**Base Case:**
In the base case, when the matrices are of size 1x1, the complexity is constant time since there's only one element to process.

**Divide Step:**
The divide step involves splitting the input matrices into smaller submatrices. This operation has a time complexity of O(1) since it only involves index manipulation.

**Conquer Step:**
In the conquer step, the algorithm recursively computes the products of the submatrices. If we denote the size of the matrices as n, then in each recursive call, the matrices are divided into four submatrices of size n/2. Hence, the conquer step has a time complexity of T(n/2).

**Combine Step:**
In the combine step, the products of the submatrices are combined to form the final result. Since this step involves summation and multiplication of corresponding elements, its time complexity is O(n^2), where n is the size of the matrices.

**T(n)** =

{

O(1) if n = 1 (base case)

4T(n/2) + O(n^2) otherwise

}

The overall time complexity of the SMMRec algorithm is O(n^3), where n is the size of the input matrices.I guess.

###  Suggestion1. Do a tree analysis;

In [ ]:
                            T(n)
                           /  |  \
                          /   |   \
                      T(n/2) T(n/2) T(n/2) T(n/2)
                     / | \   / | \   / | \   / | \
              T(n/4) ...   T(n/4) ...   T(n/4) ...
             / | \              / | \              / | \
        T(n/8) ...          T(n/8) ...          T(n/8) ...
          / | \               / | \               / | \

In [ ]:
The number of nodes at each level of the tree:
Level 0: 1 node (root)
Level 1: 4 nodes
Level 2: 4^2 = 16 nodes
Level i: 4^i nodes

Since the tree height corresponds to the number of recursive calls until reaching the base case, and the base case occurs when n=1, the height of the tree is log2(n)

Therefore, the total number of nodes in the tree is 1+4+4^2+...+4^log2(n)   The sum of this series is: 4n-1/3

Each node represents a subproblem, and the work done at each node (excluding the base case) is O(n^2) because of the combine step.Therefore, the total complexity of the algorithm is the product of the number of nodes and the work done at each node, which gives us:

T(n) = 4n-1/3 ⋅ O(n^2) = O(n^3)

###  Suggestion2. Test and compare the practical speed with the non-recursive algorithm

In [53]:
sizes = [4,64,256]  
for size in sizes:
    A = generate_random_matrix(size)
    B = generate_random_matrix(size)
    
    # recursive algorithm
    start_time = time.time()
    result_recursive = SMM_recursive(A, B)
    recursive_time = time.time() - start_time

    # non-recursive algorithm
    start_time = time.time()
    result_non_recursive = np.dot(A, B)
    non_recursive_time = time.time() - start_time

    print(f"Matrix size: {size}x{size}")
    print(f"Recursive time: {recursive_time:.3f} s")
    print(f"Non-recursive time: {non_recursive_time:.3f} s")
    print()

Matrix size: 4x4
Recursive time: 0.002 s
Non-recursive time: 0.000 s

Matrix size: 64x64
Recursive time: 0.458 s
Non-recursive time: 0.000 s

Matrix size: 256x256
Recursive time: 37.168 s
Non-recursive time: 0.020 s



# Exercise Three
### 1. Reflect on the difference between (complexity of) addition/subtraction and multiplication on matrices.

**Addition/Subtraction Complexity:**
For addition and subtraction of matrices, the computational complexity is generally O（n^2）, where n is the size (number of rows or columns) of the matrices. This is because we simply iterate over each element of the matrices and perform addition or subtraction on corresponding elements.

**Multiplication Complexity:**
Matrix multiplication has a higher computational complexity compared to addition/subtraction. The complexity arises from the fact that each element of the resulting matrix requires a sum of products of corresponding elements from the row of the first matrix and the column of the second matrix. The complexity of the standard matrix multiplication algorithm (like the naive approach or Strassen's algorithm) is approximately O(n^3).

### 2. Do a complexity analysis of the Strassen algorithm.

**1. Base Case:**
The base case occurs when the matrices are small enough to be multiplied using a direct method, typically when the matrices reach a certain threshold size (often 2x2 or 3x3). The complexity of the base case is constant time, denoted as O(1).

**2. Divide Step:**
The divide step involves partitioning the input matrices into submatrices. In the Strassen algorithm, each matrix is divided into four submatrices of approximately half the size. This step has a time complexity of O(1) since it only involves index manipulation.  

**3. Conquer Step**
The conquer step involves recursively multiplying the submatrices and combining the results to form the final result. In each recursive call, the algorithm performs 7 recursive multiplications of submatrices of size n/2 and 18 additions or subtractions of these intermediate results. Therefore, the complexity of the conquer step can be expressed as:

T(n) = 7T(n/2) + O(n2）

**4. Combine Step:**
The combine step involves combining the results of the recursive calls to form the final result matrix. This step typically involves simple additions and subtractions of corresponding submatrices, which has a time complexity of O(n^2)

**T(n)** =

{

O(1) if n is small enough (base case)

7T(n/2) + O(n^2) ≈ O(n^2.81) otherwise

}

### Suggestion1. Implement and test the algorithm;

In [56]:
def matrix_sub(A, B):
    return [[A[i][j] - B[i][j] for j in range(len(A))] for i in range(len(A))]

def Strassen(A, B):
    n = len(A)
    if n == 1:
        # Base case
        return [[A[0][0] * B[0][0]]]  
    else:
        # Divide
        A11, A12, A21, A22 = split_matrix(A)
        B11, B12, B21, B22 = split_matrix(B)

        S1 = matrix_sub(B12, B22)
        S2 = matrix_add(A11, A12)
        S3 = matrix_add(A21, A22)
        S4 = matrix_sub(B21, B11)
        S5 = matrix_add(A11, A22)
        S6 = matrix_add(B11, B22)
        S7 = matrix_sub(A12, A22)
        S8 = matrix_add(B21, B22)
        S9 = matrix_sub(A11, A21)
        S10 = matrix_add(B11, B12)
        
        # Conquer
        P1 = Strassen(A11, S1)
        P2 = Strassen(S2, B22)
        P3 = Strassen(S3, B11)
        P4 = Strassen(A22, S4)
        P5 = Strassen(S5, S6)
        P6 = Strassen(S7, S8)
        P7 = Strassen(S9, S10)

        C11 = matrix_add(matrix_sub(matrix_add(P5, P4), P2), P6)
        C12 = matrix_add(P1, P2)
        C21 = matrix_add(P3, P4)
        C22 = matrix_sub(matrix_sub(matrix_add(P5, P1), P3), P7)

        # Combine 
        return combine_matrices(C11, C12, C21, C22)

In [61]:
# Example
A = [[1, 2, 3, 12], [4, 5, 6, 2], [9, 7, 10, 12], [11, 10, 5, 7]]
B = [[2, 14, 8, 5], [8, 17, 2, 2], [16, 4, 10, 12], [12, 7, 7, 7]]

C = Strassen(A, B)
print("Strassen result:")
for row in C:
    print(row)
print()

np_result = np.dot(A, B) 
print("np result:\n", np_result)

Strassen result:
[210, 144, 126, 129]
[168, 179, 116, 116]
[378, 369, 270, 263]
[266, 393, 207, 184]

np result:
 [[210 144 126 129]
 [168 179 116 116]
 [378 369 270 263]
 [266 393 207 184]]


In [62]:
# Time comparison
sizes = [4,64,256]  
for size in sizes:
    A = generate_random_matrix(size)
    B = generate_random_matrix(size)

    # Strassen's algorithm
    start_time = time.time()
    result_strassen = Strassen(A, B)
    strassen_time = time.time() - start_time
    
    # Recursive algorithm
    start_time = time.time()
    result_recursive = SMMRec(A, B)
    recursive_time = time.time() - start_time

    # Non-recursive algorithm
    start_time = time.time()
    result_non_recursive = np.dot(A, B)
    non_recursive_time = time.time() - start_time

    
    print(f"Matrix size: {size}x{size}")
    print(f"Strassen's time: {strassen_time:.3f} s")
    print(f"Recursive time: {recursive_time:.3f} s")
    print(f"Non-recursive time: {non_recursive_time:.3f} s")

Matrix size: 4x4
Strassen's time: 0.001 s
Recursive time: 0.001 s
Non-recursive time: 0.000 s
Matrix size: 64x64
Strassen's time: 0.705 s
Recursive time: 0.577 s
Non-recursive time: 0.000 s
Matrix size: 256x256
Strassen's time: 34.941 s
Recursive time: 37.086 s
Non-recursive time: 0.020 s


### Suggestion2. Discuss other optimisations;

###### **Finkel-Kanth algorithm**

FK algorithm (Finkel-Kanth algorithm) is an optimization algorithm for sparse matrix multiplication, aiming to reduce the number of multiplication operations by exploiting the sparsity property. Sparse matrices are matrices where the majority of elements are zeros.The key idea of the FK algorithm is to only compute multiplication operations for non-zero elements in sparse matrices, while ignoring zero elements. By doing so, the computational workload can be significantly reduced, leading to improved efficiency in sparse matrix multiplication.


The FK algorithm typically consists of two stages: preprocessing stage and computation stage.

**1 Preprocessing Stage:**
In the preprocessing stage, the input sparse matrix undergoes some preprocessing operations to determine which elements are non-zero and their positions. This can be achieved by scanning the rows and columns of the sparse matrix and storing the positions of non-zero elements in a data structure, such as compressed sparse row (CSR) or compressed sparse column (CSC) representation.

**2 Computation Stage：**
In the computation stage, utilizing the positions of non-zero elements obtained from the preprocessing stage, multiplication operations are only performed for these non-zero elements. This means that for two sparse matrices A and B, multiplication operations are only performed when there are non-zero elements in the same position in row i of matrix A and column j of matrix B, and the results are accumulated at the corresponding position in the product matrix.

Here is an example that explains the two stages

In [65]:
def preprocess_sparse_matrix(matrix):
    non_zero_positions = []
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if matrix[i][j] != 0:
                non_zero_positions.append((i, j))
    return non_zero_positions

def finkel_kanth_multiply(A, B):
    # Preprocessing stage
    non_zero_positions_A = preprocess_sparse_matrix(A)
    non_zero_positions_B = preprocess_sparse_matrix(B)
    
    # Computation stage
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i, j in non_zero_positions_A:
        for k, l in non_zero_positions_B:
            if j == k:  # Only perform multiplication when the column index of A matches the row index of B
                result[i][l] += A[i][j] * B[k][l]
    return result

# Example
A = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
B = [[4, 0, 0], [0, 5, 0], [0, 0, 6]]

print("Preprocessing stage:")
print("Non-zero positions in matrix A:", preprocess_sparse_matrix(A))
print("Non-zero positions in matrix B:", preprocess_sparse_matrix(B))
print()

print("Computation stage:")
result = finkel_kanth_multiply(A, B)
for row in result:
    print(row)


Preprocessing stage:
Non-zero positions in matrix A: [(0, 0), (1, 1), (2, 2)]
Non-zero positions in matrix B: [(0, 0), (1, 1), (2, 2)]

Computation stage:
[4, 0, 0]
[0, 10, 0]
[0, 0, 18]



**Advantages:** Reduction in the number of multiplication operations, especially for sparse matrices, leading to significant computational savings.Improved efficiency by ignoring zero elements, particularly beneficial for large sparse matrices.

**Limitations:** The preprocessing stage may require additional time and space to determine the positions of non-zero elements in sparse matrices, especially for extremely sparse matrices.The FK algorithm is suitable for sparse matrices and may not perform as well as traditional matrix multiplication algorithms for dense matrices.